trigger:
- main

pool:
  vmImage: Ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configiration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'